### ISSUE TITLE
Woodpecker Question

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/4-review#10]
@rivlev 
For the Denominator of the formula using Bayes Theorem:
![image-1](https://user-images.githubusercontent.com/25493211/34065167-44028ce4-e1cd-11e7-9184-46567705f6c6.jpg)
Is this correct? If so,
![img_1604](https://user-images.githubusercontent.com/25493211/34065396-4f560ef2-e1cf-11e7-93a5-cd0bd7a91189.jpg)
![img_1605](https://user-images.githubusercontent.com/25493211/34065400-56c03320-e1cf-11e7-8ac4-daca4eca948f.jpg)
Because the bird could be 19 inches, and neither Ivory nor Pileated

**Comment by MichaelGregg** [comment]
I am confused on wether to use ¬Ivory or Pileated in the second half of the denominator @rivlev

**Comment by rivlev** [comment]
The question was amended to specify that the bird is pileated if it is not ivory, and the probability of pileated is therefore 1-p(ivory). Sorry for the confusion.
