### ISSUE TITLE
Bayes Net Wrapper Question

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/4-review#11]
@rivlev For this question:
![screen shot 2017-12-15 at 10 33 37 pm](https://user-images.githubusercontent.com/25493211/34067018-27d6c3bc-e1e8-11e7-915a-d434e6a3fe29.png)
Why can the second network correctly represent P(Flavor, Wrapper, Shape)  ?
The solutions manual explains it by stating "(ii) is fully connected, so it can represent any joint distribution.", but i still do not undersatnd.  I thought the arrows implied causality, which would make network ii incorrect

**Comment by rivlev** [comment]
Arrows mean conditional dependence: that for variable V and parent P, p(V|P) is equal to p(V|P, other variables already in network)
We would like it to imply causality, but that requires domain knowledge when constructing the network.

Trivially, P(F|S, W) (its two parents) is equal to P(F|S, W) (the variables already in the network)
P(W) (no parents) is not equal to P(W|S) (round candy is more likely to be strawberry, which is more likely to be red)
