### ISSUE TITLE
#3.3 Gradient of the cost function w.r.t a5

### ISSUE THREAD

**Issue by bharat1097** [cisc3410/4-review#15]
I understand that the derivative after replacing "y-hat" (the second-term in the cost function) with a5 with respect to a5 is (a5-y). But can someone please explain why we replace "y-hat" with a5 in the first place?

@rivlev

**Comment by rivlev** [comment]
y-hat is the predicted label
a5 is the predicted label (the output of the entire neural network)

Neural network solution now posted [here](https://photos.app.goo.gl/8RphLbBU8OtJ8iPJ2)
