### ISSUE TITLE
Probability 

### ISSUE THREAD

**Issue by officialmike** [cisc3410/4-review#17]
Hi @rivlev, 

In the solution posted for the ivory-billed woodpecker question, P(pileated) is treated the same as P(!ivory) (1-10^-6). But the question states that P(pileated) is 1/50. Why do we we multiply P(19in|pileated) and P(!ivory) if pileated does not cover all cases of !ivory?

**Comment by bharat1097** [comment]
@officialmike She mentioned in class the correct probability is in fact (1-10^-6), and that she shouldn't have given 1/50.

**Comment by officialmike** [comment]
@bharat1097 thanks
