### ISSUE TITLE
HW Question 2 PDF

### ISSUE THREAD

**Issue by bharat1097** [cisc3410/4-review#4]
Hi Prof. @rivlev , 
Where can we find the PDF to Question 2 of the HW.

Thanks, 
Bharat

**Comment by rivlev** [comment]
https://drive.google.com/open?id=1tVd2Z6aqT7Bt7fRG6RdOPZVxZ3fWsBP6
Linked from the class website now

**Comment by myang310** [comment]
What's the class website? I don't see it on http://www.sci.brooklyn.cuny.edu/~levitan/ai/

**Comment by midwestmonika** [comment]
http://www.sci.brooklyn.cuny.edu/~levitan/ai/materials/
