### ISSUE TITLE
submission issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/4-review#6]
@rivlev I emailed it to you because when i tried to submit it i got this message:
![screen shot 2017-12-14 at 12 33 37 am](https://user-images.githubusercontent.com/25493211/33976978-7aba1742-e066-11e7-9e8b-f12059989d8f.png)
Does email suffice? If not what should i do in order to submit it?

**Comment by rivlev** [comment]
there is a space between ```image``` and ```3.jpeg```
