### ISSUE TITLE
submission issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/4-review#7]
@rivlev I encountered the 'src refspec does not match any' error, so i made a dummy change, and then committed it, then this is what happens when i tried to push it:
![screen shot 2017-12-14 at 1 01 30 am](https://user-images.githubusercontent.com/25493211/33977755-68252e6a-e06a-11e7-93a1-a7dba67016fc.png)

**Comment by h01m3s** [comment]
You should always clone from https://github.com/cisc3410/4-review-yourname, NOT https://github.com/cisc3410/4-review. Otherwise you won't have permission to push.

Try following command in your homework 4 folder.
```
git remote add somename https://github.com/cisc3410/4-review-yourname
git push somename hw
```
