### ISSUE TITLE
Review for final

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/4-review#8]
@rivlev I am having trouble understanding how to do #1.1 on the Final Review (woodpecker question).  Could you please explain how to complete it?  I understand the Bayes theorem aspect, but what i am struggling with is the denominator of the formula in this case.  Also, in addition to this review, and the definitions you provided for us, what type of question should i know how to do to be prepared for the final? Thank you

**Comment by MichaelGregg** [comment]
@rivlev Also, i am having trouble understanding how to calculate question #2-B.  How do i calculate the probability of the dragon being home on day 3? Thank you

**Comment by bharat1097** [comment]
@MichaelGregg  For question 2B:

![image](https://user-images.githubusercontent.com/25468036/34018917-4004040c-e0fa-11e7-92de-e9c1121f8a08.png)

**Comment by bharat1097** [comment]
@MichaelGregg  For 1.1:
![image](https://user-images.githubusercontent.com/25468036/34018954-659fcb10-e0fa-11e7-9460-1d57807762ab.png)

**Comment by MichaelGregg** [comment]
@bharat1097 thank you i appreciate the assistance

**Comment by MichaelGregg** [comment]
@bharat1097 What calculations did you do to normalize the values for 2B?

**Comment by bharat1097** [comment]
@MichaelGregg  normalize(0.00336, 0.00192) = (0.00336/(0.00336+0.00192), 0.00192/(0.00336+0.00192))

**Comment by MichaelGregg** [comment]
@bharat1097 Got it thank you

**Comment by MichaelGregg** [comment]
@bharat1097 Could you explain the answers to this set of questions?
![screen shot 2017-12-14 at 7 13 11 pm](https://user-images.githubusercontent.com/25493211/34020556-f3d25d3c-e102-11e7-883d-dcd9cd3db943.png)

**Comment by bharat1097** [comment]
@MichaelGregg  I've opened an issue with the Solutions to the textbook exercises you can find the solution in that.
