### ISSUE TITLE
Review Question

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/4-review#9]
@rivlev For question 2-a when calculating the entropy for 'sticky' i have to do the calculation (1/4)log(1/4).  Using my calculator, doing log base 2, in degrees or radians does not make a difference, i get (1/4)log(1/4)=-0.15.  But in office hours when we reviewed, according to you (1/4)log(1/4)=-0.5.  Am i doing something wrong?

**Comment by bharat1097** [comment]
@MichaelGregg  you're calculator is giving you answers in Log base 10. Try figuring out in the Calculator manual or on the internet about how to change base of the log. If you use the Google calculator, you can just say log2(x), where x > 0.

**Comment by MichaelGregg** [comment]
@bharat1097 got it thanks a lot
